export const fakeOffer = {
  bedrooms: 1,
  city: {
    name: 'Paris',
    location: {
      latitude: 48.85661,
      longitude: 2.351499,
      zoom: 13,
    }},
  description: 'Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.',
  goods: [
    'Laptop friendly workspace', 'Breakfast', 'Washer',
    'Laptop friendly workspace',
    'Breakfast',
    'Washer',
  ],
  host: {
    id: 25,
    name: 'Angelina',
    isPro: true,
    avatarUrl: 'img/avatar-angelina.jpg',
  },
  id: 1,
  images: [
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/18.jpg',
    'https://8.react.pages.academy/static/hotel/16.jpg',
    'https://8.react.pages.academy/static/hotel/12.jpg',
    'https://8.react.pages.academy/static/hotel/1.jpg',
    'https://8.react.pages.academy/static/hotel/6.jpg',
    'https://8.react.pages.academy/static/hotel/8.jpg',
    'https://8.react.pages.academy/static/hotel/20.jpg',
    'https://8.react.pages.academy/static/hotel/4.jpg',
    'https://8.react.pages.academy/static/hotel/13.jpg',
    'https://8.react.pages.academy/static/hotel/10.jpg',
    'https://8.react.pages.academy/static/hotel/17.jpg',
    'https://8.react.pages.academy/static/hotel/7.jpg',
    'https://8.react.pages.academy/static/hotel/14.jpg',
  ],
  isFavorite: false,
  isPremium: true,
  location: {
    latitude: 48.83861,
    longitude: 2.350499,
    zoom: 16,
  },
  maxAdults: 3,
  previewImage: 'https://8.react.pages.academy/static/hotel/19.jpg',
  price: 203,
  rating: 2,
  title: 'Perfectly located Castro',
  type: 'room',
};

export const fakeOffers = [{
  bedrooms: 1,
  city: {
    name: 'Paris',
    location: {
      latitude: 48.85661,
      longitude: 2.351499,
      zoom: 13,
    }},
  description: 'Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.',
  goods: [
    'Laptop friendly workspace', 'Breakfast', 'Washer',
    'Laptop friendly workspace',
    'Breakfast',
    'Washer',
  ],
  host: {
    id: 25,
    name: 'Angelina',
    isPro: true,
    avatarUrl: 'img/avatar-angelina.jpg',
  },
  id: 1,
  images: [
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/18.jpg',
    'https://8.react.pages.academy/static/hotel/16.jpg',
    'https://8.react.pages.academy/static/hotel/12.jpg',
    'https://8.react.pages.academy/static/hotel/1.jpg',
    'https://8.react.pages.academy/static/hotel/6.jpg',
    'https://8.react.pages.academy/static/hotel/8.jpg',
    'https://8.react.pages.academy/static/hotel/20.jpg',
    'https://8.react.pages.academy/static/hotel/4.jpg',
    'https://8.react.pages.academy/static/hotel/13.jpg',
    'https://8.react.pages.academy/static/hotel/10.jpg',
    'https://8.react.pages.academy/static/hotel/17.jpg',
    'https://8.react.pages.academy/static/hotel/7.jpg',
    'https://8.react.pages.academy/static/hotel/14.jpg',
  ],
  isFavorite: false,
  isPremium: true,
  location: {
    latitude: 48.83861,
    longitude: 2.350499,
    zoom: 16,
  },
  maxAdults: 3,
  previewImage: 'https://8.react.pages.academy/static/hotel/19.jpg',
  price: 203,
  rating: 2,
  title: 'Perfectly located Castro',
  type: 'room',
},
{
  bedrooms: 1,
  city: {
    name: 'Paris',
    location: {
      latitude: 48.85661,
      longitude: 2.351499,
      zoom: 13,
    }},
  description: 'Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.',
  goods: [
    'Laptop friendly workspace', 'Breakfast', 'Washer',
    'Laptop friendly workspace',
    'Breakfast',
    'Washer',
  ],
  host: {
    id: 26,
    name: 'Angelina',
    isPro: true,
    avatarUrl: 'img/avatar-angelina.jpg',
  },
  id: 2,
  images: [
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/18.jpg',
    'https://8.react.pages.academy/static/hotel/16.jpg',
    'https://8.react.pages.academy/static/hotel/12.jpg',
    'https://8.react.pages.academy/static/hotel/1.jpg',
    'https://8.react.pages.academy/static/hotel/6.jpg',
    'https://8.react.pages.academy/static/hotel/8.jpg',
    'https://8.react.pages.academy/static/hotel/20.jpg',
    'https://8.react.pages.academy/static/hotel/4.jpg',
    'https://8.react.pages.academy/static/hotel/13.jpg',
    'https://8.react.pages.academy/static/hotel/10.jpg',
    'https://8.react.pages.academy/static/hotel/17.jpg',
    'https://8.react.pages.academy/static/hotel/7.jpg',
    'https://8.react.pages.academy/static/hotel/14.jpg',
  ],
  isFavorite: false,
  isPremium: true,
  location: {
    latitude: 48.83861,
    longitude: 2.350499,
    zoom: 16,
  },
  maxAdults: 3,
  previewImage: 'https://8.react.pages.academy/static/hotel/19.jpg',
  price: 203,
  rating: 2,
  title: 'Perfectly located Castro',
  type: 'room',
},
];

export const fakeOffersWithFavoritesStatus = [{
  bedrooms: 1,
  city: {
    name: 'Paris',
    location: {
      latitude: 48.85661,
      longitude: 2.351499,
      zoom: 13,
    }},
  description: 'Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.',
  goods: [
    'Laptop friendly workspace', 'Breakfast', 'Washer',
    'Laptop friendly workspace',
    'Breakfast',
    'Washer',
  ],
  host: {
    id: 25,
    name: 'Angelina',
    isPro: true,
    avatarUrl: 'img/avatar-angelina.jpg',
  },
  id: 1,
  images: [
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/18.jpg',
    'https://8.react.pages.academy/static/hotel/16.jpg',
    'https://8.react.pages.academy/static/hotel/12.jpg',
    'https://8.react.pages.academy/static/hotel/1.jpg',
    'https://8.react.pages.academy/static/hotel/6.jpg',
    'https://8.react.pages.academy/static/hotel/8.jpg',
    'https://8.react.pages.academy/static/hotel/20.jpg',
    'https://8.react.pages.academy/static/hotel/4.jpg',
    'https://8.react.pages.academy/static/hotel/13.jpg',
    'https://8.react.pages.academy/static/hotel/10.jpg',
    'https://8.react.pages.academy/static/hotel/17.jpg',
    'https://8.react.pages.academy/static/hotel/7.jpg',
    'https://8.react.pages.academy/static/hotel/14.jpg',
  ],
  isFavorite: true,
  isPremium: true,
  location: {
    latitude: 48.83861,
    longitude: 2.350499,
    zoom: 16,
  },
  maxAdults: 3,
  previewImage: 'https://8.react.pages.academy/static/hotel/19.jpg',
  price: 203,
  rating: 2,
  title: 'Perfectly located Castro',
  type: 'room',
},
{
  bedrooms: 1,
  city: {
    name: 'Paris',
    location: {
      latitude: 48.85661,
      longitude: 2.351499,
      zoom: 13,
    }},
  description: 'Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.',
  goods: [
    'Laptop friendly workspace', 'Breakfast', 'Washer',
    'Laptop friendly workspace',
    'Breakfast',
    'Washer',
  ],
  host: {
    id: 26,
    name: 'Angelina',
    isPro: true,
    avatarUrl: 'img/avatar-angelina.jpg',
  },
  id: 2,
  images: [
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/18.jpg',
    'https://8.react.pages.academy/static/hotel/16.jpg',
    'https://8.react.pages.academy/static/hotel/12.jpg',
    'https://8.react.pages.academy/static/hotel/1.jpg',
    'https://8.react.pages.academy/static/hotel/6.jpg',
    'https://8.react.pages.academy/static/hotel/8.jpg',
    'https://8.react.pages.academy/static/hotel/20.jpg',
    'https://8.react.pages.academy/static/hotel/4.jpg',
    'https://8.react.pages.academy/static/hotel/13.jpg',
    'https://8.react.pages.academy/static/hotel/10.jpg',
    'https://8.react.pages.academy/static/hotel/17.jpg',
    'https://8.react.pages.academy/static/hotel/7.jpg',
    'https://8.react.pages.academy/static/hotel/14.jpg',
  ],
  isFavorite: false,
  isPremium: true,
  location: {
    latitude: 48.83861,
    longitude: 2.350499,
    zoom: 16,
  },
  maxAdults: 3,
  previewImage: 'https://8.react.pages.academy/static/hotel/19.jpg',
  price: 203,
  rating: 2,
  title: 'Perfectly located Castro',
  type: 'room',
},
];

export const fakeOfferFromServer = {
  bedrooms: 1,
  city: {
    name: 'Paris',
    location: {
      latitude: 48.85661,
      longitude: 2.351499,
      zoom: 13,
    }},
  description: 'Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.',
  goods: [
    'Laptop friendly workspace', 'Breakfast', 'Washer',
    'Laptop friendly workspace',
    'Breakfast',
    'Washer',
  ],
  host: {
    id: 25,
    name: 'Angelina',
    'is_pro': true,
    'avatar_url': 'img/avatar-angelina.jpg',
  },
  id: 1,
  images: [
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/18.jpg',
    'https://8.react.pages.academy/static/hotel/16.jpg',
    'https://8.react.pages.academy/static/hotel/12.jpg',
    'https://8.react.pages.academy/static/hotel/1.jpg',
    'https://8.react.pages.academy/static/hotel/6.jpg',
    'https://8.react.pages.academy/static/hotel/8.jpg',
    'https://8.react.pages.academy/static/hotel/20.jpg',
    'https://8.react.pages.academy/static/hotel/4.jpg',
    'https://8.react.pages.academy/static/hotel/13.jpg',
    'https://8.react.pages.academy/static/hotel/10.jpg',
    'https://8.react.pages.academy/static/hotel/17.jpg',
    'https://8.react.pages.academy/static/hotel/7.jpg',
    'https://8.react.pages.academy/static/hotel/14.jpg',
  ],
  'is_favorite': false,
  'is_premium': true,
  location: {
    latitude: 48.83861,
    longitude: 2.350499,
    zoom: 16,
  },
  'max_adults': 3,
  'preview_image': 'https://8.react.pages.academy/static/hotel/19.jpg',
  price: 203,
  rating: 2,
  title: 'Perfectly located Castro',
  type: 'room',
};

export const fakeOffersFromServer = [{
  bedrooms: 1,
  city: {
    name: 'Paris',
    location: {
      latitude: 48.85661,
      longitude: 2.351499,
      zoom: 13,
    }},
  description: 'Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.',
  goods: [
    'Laptop friendly workspace', 'Breakfast', 'Washer',
    'Laptop friendly workspace',
    'Breakfast',
    'Washer',
  ],
  host: {
    id: 25,
    name: 'Angelina',
    'is_pro': true,
    'avatar_url': 'img/avatar-angelina.jpg',
  },
  id: 1,
  images: [
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/18.jpg',
    'https://8.react.pages.academy/static/hotel/16.jpg',
    'https://8.react.pages.academy/static/hotel/12.jpg',
    'https://8.react.pages.academy/static/hotel/1.jpg',
    'https://8.react.pages.academy/static/hotel/6.jpg',
    'https://8.react.pages.academy/static/hotel/8.jpg',
    'https://8.react.pages.academy/static/hotel/20.jpg',
    'https://8.react.pages.academy/static/hotel/4.jpg',
    'https://8.react.pages.academy/static/hotel/13.jpg',
    'https://8.react.pages.academy/static/hotel/10.jpg',
    'https://8.react.pages.academy/static/hotel/17.jpg',
    'https://8.react.pages.academy/static/hotel/7.jpg',
    'https://8.react.pages.academy/static/hotel/14.jpg',
  ],
  'is_favorite': false,
  'is_premium': true,
  location: {
    latitude: 48.83861,
    longitude: 2.350499,
    zoom: 16,
  },
  'max_adults': 3,
  'preview_image': 'https://8.react.pages.academy/static/hotel/19.jpg',
  price: 203,
  rating: 2,
  title: 'Perfectly located Castro',
  type: 'room',
},
{
  bedrooms: 1,
  city: {
    name: 'Paris',
    location: {
      latitude: 48.85661,
      longitude: 2.351499,
      zoom: 13,
    }},
  description: 'Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.',
  goods: [
    'Laptop friendly workspace', 'Breakfast', 'Washer',
    'Laptop friendly workspace',
    'Breakfast',
    'Washer',
  ],
  host: {
    id: 26,
    name: 'Angelina',
    'is_pro': true,
    'avatar_url': 'img/avatar-angelina.jpg',
  },
  id: 2,
  images: [
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/15.jpg',
    'https://8.react.pages.academy/static/hotel/18.jpg',
    'https://8.react.pages.academy/static/hotel/16.jpg',
    'https://8.react.pages.academy/static/hotel/12.jpg',
    'https://8.react.pages.academy/static/hotel/1.jpg',
    'https://8.react.pages.academy/static/hotel/6.jpg',
    'https://8.react.pages.academy/static/hotel/8.jpg',
    'https://8.react.pages.academy/static/hotel/20.jpg',
    'https://8.react.pages.academy/static/hotel/4.jpg',
    'https://8.react.pages.academy/static/hotel/13.jpg',
    'https://8.react.pages.academy/static/hotel/10.jpg',
    'https://8.react.pages.academy/static/hotel/17.jpg',
    'https://8.react.pages.academy/static/hotel/7.jpg',
    'https://8.react.pages.academy/static/hotel/14.jpg',
  ],
  'is_favorite': false,
  'is_premium': true,
  location: {
    latitude: 48.83861,
    longitude: 2.350499,
    zoom: 16,
  },
  'max_adults': 3,
  'preview_image': 'https://8.react.pages.academy/static/hotel/19.jpg',
  price: 203,
  rating: 2,
  title: 'Perfectly located Castro',
  type: 'room',
},
];
